# Generated by Django 5.1.5 on 2025-01-27 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора объявления",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите объявление, под которым указан отзыв",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="advertisements.announcement",
                verbose_name="Объявление, под которым указан отзыв",
            ),
        ),
    ]
