# Generated by Django 5.1.5 on 2025-01-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0003_alter_announcement_author_alter_review_ad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["title", "price", "description", "author", "-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
